name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.3.0]
        java: ['8', '11', '17']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test